version: '3.8'

services:
  frontend:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`mypland.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.middlewares.frontend-spa.redirectregex.permanent=false"
      - "traefik.http.middlewares.frontend-spa.redirectregex.regex=^(?!.*\\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$).*$"
      - "traefik.http.middlewares.frontend-spa.redirectregex.replacement=/index.html"
      - "traefik.http.routers.frontend.middlewares=frontend-spa"
    restart: unless-stopped

  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped
