version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Optional: Add backend service if needed
  # backend:
  #   build: ../projectflow-backend
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=production
  #   restart: unless-stopped
